patchedDependencies:
  builtin-modules@5.0.0: patches/builtin-modules@5.0.0.patch

allowBuilds:
  '@swc/core': true
  cbor-extract: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
